### ISSUE TITLE
order of package loading

### ISSUE THREAD

**Issue by ringprince** [tudo-r/BatchJobs#104]
The order of the packages to be loaded in each job is not respected.  It seems that packages are loaded in alphabetical order.  But the correct order in which to load packages is important in some cases!

For instance, with

     regmdb <- makeRegistry(id="test",
                            file.dir="test",
                            packages=c("plyr", "dplyr"),
                            work.dir="test")

I get in each job

     Loading required package: dplyr
     Loading required package: plyr
     ------------------------------------------------------------------------------
     You have loaded plyr after dplyr - this is likely to cause problems.
     If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
     library(plyr); library(dplyr)
     ------------------------------------------------------------------------------
     ...

and a lot of problems resulting from masked functions.

**Comment by mllg** [comment]
Should be fixed now. Re-open if you experience further problems.
