### ISSUE TITLE
Results from BatchJobs are what they should be *-1 + job number?

### ISSUE THREAD

**Issue by rosemm** [tudo-r/BatchJobs#107]
I am running a minimal example using BatchJobs, and the results are not as expected. I'm using the global_config settings (https://github.com/tudo-r/BatchJobs/wiki/Configuration), with debug=TRUE. I am running the following code in R on my HPC server:

    > sessionInfo()
    R version 3.1.2 (2014-10-31)
    Platform: x86_64-unknown-linux-gnu (64-bit)

    locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
     [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
     [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
     [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    > library(BatchJobs)
    Loading required package: BBmisc
    Sourcing configuration file: '/ibrix/packages/R/3.1.2/lib64/R/library/BatchJobs/etc/BatchJobs_global_config.R'
    Sourcing configuration file: '/home15/rosem/.BatchJobs.R'
    Sourcing configuration file: '/ibrix/home15/rosem/.BatchJobs.R'
    BatchJobs configuration:
      cluster functions: Interactive
      mail.from: 
      mail.to: 
      mail.start: none
      mail.done: none
      mail.error: none
      default.resources: 
      debug: TRUE
      raise.warnings: FALSE
      staged.queries: TRUE
      max.concurrent.jobs: Inf
      fs.timeout: NA

    > reg <- makeRegistry(id = "batchtest")
    Creating dir: /ibrix/home15/rosem/batchtest-files
    Saving registry: /ibrix/home15/rosem/batchtest-files/registry.RData
    > 
    > batchMap(reg, identity, 1)
    Adding 1 jobs to DB.
    > submitJobs(reg)
    Saving conf: /ibrix/home15/rosem/batchtest-files/conf.RData
    Submitting 1 chunks / 1 jobs.
    Cluster functions: Interactive.
    Auto-mailer settings: start=none, done=none, error=none.
    Writing 1 R scripts...
    SubmitJobs |+++++++++++++++++++++++++++++++++++++++++++++++++| 100% (00:00:00)
    Sending 1 submit messages...
    Might take some time, do not interrupt this!
    > showStatus(reg)
    Syncing registry ...
    Status for 1 jobs at 2015-11-07 14:18:03 
    Submitted: 1 (100.00%)
    Started:   1 (100.00%)
    Running:   0 (  0.00%)
    Done:      1 (100.00%)
    Errors:    0 (  0.00%)
    Expired:   0 (  0.00%)
    Time: min=0.00s avg=0.00s max=0.00s
    > load("batchtest-files/jobs/01/1-result.RData")
    > 1-result
    [1] 0

If I run batchMap(reg, identity, 2) the result is -1, and with batchMap(reg, identity, 3) the result is -2. Any ideas why this might be happening? The identity function should just return the argument (so it should be 1 for the code above). I find the same issue with other functions. For example, if I use mean(rnorm(100, mean=100)) for the function I send to batchMap, I end up with results around -99. If I run this on multiple nodes (and I change the configuration, so cluster.functions = makeClusterFunctionsTorque('simple.tmpl'), using the template from https://raw.githubusercontent.com/tudo-r/BatchJobs/master/examples/cfTorque/simple.tmpl), the results from each node are around -100 + node number (so the results from the 5th node are around -95).

(I posted this on stack exchange http://stackoverflow.com/questions/33588269/batchjobs-results-gives-the-function-result-1-job before I thought to use the issue tracker here - apologies for double-posting.)

**Comment by surmann** [comment]
Try an `ls()`. Probably the correct result from the `load` command is stored in the variable `result`. When you calculate `1-result` you will get exactly the results you described.

**Comment by rosemm** [comment]
Oh man, that's totally it. I was imagining the variable name would match the file name, even though of course you can't have a - in a variable name in R. I guess I've been staring at this too long. Thanks so much for your help!

**Comment by surmann** [comment]
You´re welcome.

**Comment by berndbischl** [comment]
Thanks Dirk!
