### ISSUE TITLE
LSF submitJobs issue

### ISSUE THREAD

**Issue by ashokrags** [tudo-r/BatchJobs#116]
hi,
  great package. Just wanted to know if i was doing something wrong or if its a bug. Whenever, i submit jobs, I find that the first and the last job die, but all the jobs in between run. For example, if I run 10 jobs, jobs 1 and 10, fail. So, as a workaround I currently submit two dummy jobs in the beginning and the end. But, I was wondering if this is some user error somehow and i get the same error messages for both the first and the last jobs:
`Error : is.list(control) is not TRUE

Error in doWithOneRestart(return(expr), restart) : bad error message

Calls: <Anonymous> -> sendMail -> warningf`

**Comment by berndbischl** [comment]
this is with 99% probability related to the sendmailr mailing option.

i am guessing you are sending mails with the "first+last" option?

2 ways out now

a) disable status emails. you really dont need them so much to use the package.
at least this is much better than doing this "dummy job" workaround ;-)

b) debug what is wrong. you seem to have setup your mailing options wrongly.
also please paste your BatchJobs config file here.

**Comment by ashokrags** [comment]
Thanks for getting back to me so quickly. See below for my config. I will  disable the mailing options and see if that fixes the error.  I didn't specify any mail options assuming that it would use my default cluster account settings?? I guess this is where it failed. I can check and let you know if its needed :)

`mail.start = "first+last"
mail.done = "first+last"
mail.error = "all"
default.resources=list(queue="medium")
db.driver = "SQLite"
db.options = list()
debug = FALSE`

**Comment by berndbischl** [comment]
setting the sendmailr options correctly can be a bit tricky. 
look into the sendmailr docs and try to set this here:

mail.control = list(smtpServer="my.mail.server.com")

or disable mails.

reopen if you need further help
