### ISSUE TITLE
Reason for sudden updates + release on this deprecate package?

### ISSUE THREAD

**Issue by HenrikBengtsson** [tudo-r/BatchJobs#126]
What was the reason for the sudden burst of updates and the CRAN release on this deprecated package?  Are you reviving it?

**Comment by berndbischl** [comment]
no i had to, becuase i need to change BBmisc. 

we have a function isFALSE in there, which i need to remove as this will be included in base R 3.5.0

so i cleaned up down the line

**Comment by berndbischl** [comment]
batchtools will be the standard from now on, and that belongs to Michel @mllg

**Comment by berndbischl** [comment]
i actually would like to remove BatchJobs from CRAN, but I dont want to hurt anybody still using it

**Comment by HenrikBengtsson** [comment]
Thanks for clarifying / confirming that the plans are still the same.

**Comment by berndbischl** [comment]
no problem, you are welcome
