### ISSUE TITLE
conda env activation in template?

### ISSUE THREAD

**Issue by nick-youngblut** [tudo-r/BatchJobs#128]
Researchers in my lab use `conda` to manage all bioinformatics software, including python and R packages. We have an available SGE cluster, and to submit jobs to the cluster that require a specific conda environment, we have to include the following the job submission script: `source activate MY_CONDA_ENV`. Can this line be added to the BatchJobs SGE template? Can the user specify the particular conda environment via `makeClusterFunctionsSGE` or `submitJob`?

**Comment by berndbischl** [comment]
can you please raise this issue here?
https://github.com/mllg/batchtools
we dont maintain BatchJobs anymore but continue work on batchtools
