### ISSUE TITLE
loadRegistry() with modified working directory

### ISSUE THREAD

**Issue by surmann** [tudo-r/BatchJobs#60]
Hallo @All,

I submitted a job in linux with the server working directory `/home/<name>/working`. This directory is available in Windows as `H:\working`.
If I load the registry in windows during the running job with `loadRegistry("name", getwd())`, `BatchJobs` will load the registry and change the working directory immediately. This results logically in an error for unsubmitted jobs on the linux machine.

Possible solution:
Show a message in `loadRegistry()` which will ask the user if she or he really wants to change the working directory.
Add a sentence to the documentation to describe this behaviour which enables the user to realise this problem.

Alternative idea:
Save two working directories. The first is the working directory in which the script started and needs a special function or option to be changed. The second working directory is the current one, in which the user works with the registry.

Regards,
Dirk

**Comment by mllg** [comment]
> If I load the registry in windows during the running job with loadRegistry("name", getwd()), BatchJobs will load the registry and change the working directory immediately. This results logically in an error for unsubmitted jobs on the linux machine.

Why do you not simply drop the 2nd argument for `loadRegistry`? If it is missing, BJ will not touch it. But IMHO the major problem in your setup is the `file.dir`. I've added a note in b51dae986939e9d024e5cecef83a421822e93aeb, but besides that I don't think we can do anything about it.

Did you consider using rsync and do your interim analyses on the local copy of the file dir?
