### ISSUE TITLE
time.running and time.done are not available for jobs with errors

### ISSUE THREAD

**Issue by larskotthoff** [tudo-r/BatchJobs#61]
It would be useful to have this information returned by `getJobInfo()` to e.g. see how long it would take to reproduce an error.

**Comment by berndbischl** [comment]
you are right. but unfortunately this is harder to fix then i thought.

a) either we write into DB field "done" the event time of the error. but this implies many code changes, as we use the NA there to indicate that a job, well, is not_done. i would rather stay with this.

b) we could log the time of the error into time.error

**Comment by berndbischl** [comment]
I fixed this. I dont like that I had to change the DB, but done.

@mllg Could you please check this? BE should not break right?

I also took care of updateRegistry.

Anything else to consider?

**Comment by mllg** [comment]
Checked, looks solid.
