### ISSUE TITLE
short hand function for restarting BatchJobs Registry

### ISSUE THREAD

**Issue by jakob-r** [tudo-r/BatchJobs#64]
A lot of times i find myself restarting BatchJobs like that:

```r
reg = loadRegistry(file.dir = "foo-files")
new.jobs = setdiff(getJobIds(reg), findDone(reg))
submitJobs(reg, new.jobs)
```

This obviously has some mistakes as it does not take running jobs into account. So it would be very handy to have a function like `loadRegistryAndSubmitJobs(file.dir = "foo-files", include.errored = FALSE, include.expired = TRUE, include.running = FALSE)`
Thoughts on this?

**Comment by mllg** [comment]
I've written something like this myself many times. But `setdiff(getJobIds(reg), findDone(reg))` will causes errors if there are still jobs on the system. Situations where you need to automatically resubmit errors are really rare, too. You probably will just reproduce the errors. Same for expired (except you employ your own resume mechanism like in mlrMBO).  You cannot resubmit running jobs, so this option is not very useful?

**Comment by jakob-r** [comment]
If walltime/memory was to low... So "automatic" not necessarily. But a bit more handy i'd like to see and running jobs can be opt out.

**Comment by berndbischl** [comment]
I guess we dont do this now
