### ISSUE TITLE
Method to delete registry, e.g. removeRegistry(reg)?

### ISSUE THREAD

**Issue by HenrikBengtsson** [tudo-r/BatchJobs#66]
I don't recall ever seeing a method for safely/robustly removing an existing registry, i.e. a `removeRegistry()` function. The function should check if there registry is active/used/locked etc., before trying to remove the registry and it's directory.  Does such a function exists somewhere?  

Here's a sketch but I don't know enough of the inner bits and details to know if it is the proper way to remove a registry:
```r
removeRegistry <- function(reg, ...) {
  checkRegistry(reg)
  syncRegistry(reg) 
  running = findOnSystem(reg)
  if (length(running) > 0L)
    stopf("Can't remove registry, because there are %d live jobs on the system.", length(running))
  removeDirs(reg$file.dir, recursive=TRUE, mustWork=TRUE)
}
```

**Comment by berndbischl** [comment]
I guess thats what you basically need to check: Whether there are active jobs.
Then removing the project dir deletes everything.

We never really implemented this (I guess ?) because it deletes user results....

Maybe we should have a "safety question" in there:
"Do you *really* want to do that?"
With an option to skip that, which is F by default?

**Comment by HenrikBengtsson** [comment]
Removing registry is useful in cases when there is no longer a need for the files, e.g. you have a script / function / package that uses BatchJobs as a backend for parallel/distributed processing, but after having collected the results (e.g. `loadResults()`) those jobs are obsolete/no longer of any use.

You, if one want to make sure it's not misused, then one could have `removeRegistry(..., ask=c("yes", "no"))` and if `ask == "yes" && !interactive()` an error is thrown.

About the current prototype: It feels a bit drastic to just delete the directory/files.  Shouldn't one somehow "close" the internal data base first?

**Comment by berndbischl** [comment]
> Removing registry is useful in cases when there is.......
Agreed.

> "ask"
I think this is good, too. 

Do we want something like this for makeRegistry too, when the directory already exists?
I usually have an recursive "unlink" statement in my code before makeReg (when I am developing code). I am unsure here. Maybe we should stick with the current error behavior in that case.

**Comment by HenrikBengtsson** [comment]
Thxs, then I'll add an improved version of the prototype `removeRegistry()` to the package and we're taking it from there, e.g. robustifying as/if needed.  Ok?

I'd say keep the current behavior of `makeRegistry()` for now.  If not, lets open a separate issue for that.

**Comment by berndbischl** [comment]
> add an improved version of the prototype

Please do so. Note that I will be quite busy for 2-3 days with mlr currently. We need to publish our paper there.

**Comment by HenrikBengtsson** [comment]
See commit 65c93f1.
