### ISSUE TITLE
SUGGESTION: Make ncpus=detectCores()-1 the default for makeClusterFunctionsMulticore()

### ISSUE THREAD

**Issue by HenrikBengtsson** [tudo-r/BatchJobs#67]
As a first step to get going with BatchJobs after trying the default interactive mode, I tell people to try with:
```r
cluster.functions <- makeClusterFunctionsMulticore(
  ncpus=max(1, parallel::detectCores()-1)
)
```
To make it even less "intimidating", what you think of using the above as the default value for `ncpus` so that one can just have:
```r
cluster.functions <- makeClusterFunctionsMulticore()
```
which is a minimal change from:
```r
cluster.functions <- makeClusterFunctionsInteractive()
```

I'm proposing all but one core so that one leave one core for all other things the user may do on the machine, especially if it is their local laptop.

Nothing super important; just a thought.

**Comment by mllg** [comment]
I do not see how this could possibly backfire, so feel free to change the default accordingly.

**Comment by HenrikBengtsson** [comment]
Done.

**Comment by HenrikBengtsson** [comment]
Now using
```r
ncpus = max(getOption("mc.cores", detectCores()) - 1, 1)
```
See commit 56f1494.
