### ISSUE TITLE
Does 'BatchJobs' still have to be attached, or could it be enough it's loaded?

### ISSUE THREAD

**Issue by HenrikBengtsson** [tudo-r/BatchJobs#68]
I'm trying to use 'BatchJobs' internally in a package, i.e. list it under `Imports:`.  This would only _load_ its namespace but not attach the package to the `search()` path.  However, I noticed that after creating a registry via `makeRegistry()` the package gets attached.  I tracked this down to:

``` r
  packages = union(packages, "BatchJobs")
  requirePackages(packages, stop = TRUE, suppress.warnings = TRUE, default.method = "attach") 
```

in https://github.com/tudo-r/BatchJobs/blob/master/R/Registry.R#L22-L23.

I can imagine this is a convenient setup, particularly while developing the package, but have you guys tried to see if this is still needed, i.e. it could be enough to use `loadNamespace("BatchJobs")`, say.

Just a wish, but it would be neat to not have to expose the BatchJobs API to end uses when BatchJobs is used as the backend internally.

**Comment by berndbischl** [comment]
I have complained and cursed about so many packages that do not work when they are only imported.

I can fully understand that request.

**Comment by HenrikBengtsson** [comment]
No worries; at least you do attach it, so it does work when only imported.

It's only recently with all the robustification of 'R CMD check' and so on (e.g. requirements on proper NAMESPACE imports etc.) that this really has become possible in practice (unless you control all the packages yourself).  I'm still patching my own packages here and there for this.

**Comment by berndbischl** [comment]
> It's only recently with all the robustification of 'R CMD check' and so on (e.g. requirements on proper 
> NAMESPACE imports etc.) that this really has become possible in practice 

Haha. In mlr we just changed from "require" to "requireNamespace" for all of our suggested packages. 
Because we wanted to reduce "name shadowing" and cluttering of the global NS.
It does not work at all for a large amount of packages. I lost like a month of my life to resolve this. 
There is no real check on CRAN to ensure that it works.

I complained to CRAN about this. They THEN ran a basic check. 
IIRC Kurt found like 900 packages with "improper" NS files.

**Comment by HenrikBengtsson** [comment]
However frustrating the CRAN Policy can be, particularly when it's a moving target jumping away just when you've got it fixed in your sight, I try to be positive about it; most of it really improves the overall quality of packages out there.  Imagine where we would be with 6000+ packages if we only relied on the tests available last decade.

But sure, I can see there's a growing market demand for CRAN Therapists these days.

**Comment by mllg** [comment]
You can try if c673cc54b9df60da1d5b0fe76f1756c554232d02 solves your issue (somewhat ugly, still lacking documentation for the user).

**Comment by berndbischl** [comment]
@HenrikBengtsson 
I dont want to derail this, but as one final comment: I do not really dislike the CRAN policies. Actually most stuff in there is very reasonable and R CMD check is also pretty reasonable and a useful tool.

What I dislike is: That, OTOH, I get emails about the final "period" and title style in the title of my R package,  while OTOH CRAN lives in the 80s wrt to formal unit testing. They have missed so many precious years to educate and encourage the people out there to write better software. 

And now I will stop "bickering" about this here, while @mllg actually provides something useful to the question at hand.

**Comment by HenrikBengtsson** [comment]
Something broken with commit c673cc5; I get error:
```r
  Assertion on 'packs' failed: Must be a character
```
in my job output files, e.g. *-files/jobs/01/1.out.

The error is not there in the commit just before this.

**Comment by HenrikBengtsson** [comment]
I've undone this in the master branch, cf. new commit c6ecf00.  Instead I've moved it over to branch [feature/load-only](https://github.com/tudo-r/BatchJobs/tree/feature/load-only) in case it's needed.

**Comment by mllg** [comment]
Strange. I cannot reproduce this one. Tried this with cf multicore:

```{r}
reg = batchMapQuick(identity, 1:10, packages = c("!BBmisc", "_ggplot2", "MASS"))
```

Can you update your BBmisc installation and try again (AFAIR we messed up the version numbering over there).

**Comment by HenrikBengtsson** [comment]
Reinstalled the problematic commit
```r
source("http://callr.org/install#tudo-r/BatchJobs@c673cc5")
```
verified that the correct version is installed and tried your test:
```r
library(BatchJobs)
reg <- batchMapQuick(identity, 1:10, packages = c("!BBmisc", "_ggplot2", "MASS"))
showStatus(reg)
```
which works on my end too.

However, I still get
```
Assertion on 'packs' failed: Must be a character
```
on my real-world system.  However, that relies on code that uses BatchJobs internally, so there might be something clashing with this particular commit/tweak.  I'll investigate.  I've reinstalled BBmisc from CRAN (the GitHub master branch fails to install).

BTW, it would be useful if assertion errors would be more informative, e.g.
```
Assertion on 'packs' failed: Must be a character - not NULL
```

**Comment by berndbischl** [comment]
> BTW, it would be useful if assertion errors would be more informative, e.g.

You are too slow :)

https://github.com/mllg/checkmate/issues/44

**Comment by HenrikBengtsson** [comment]
+1

**Comment by berndbischl** [comment]
> I've reinstalled BBmisc from CRAN (the GitHub master branch fails to install).

Please post the error, possibly in the tracker for BBmisc

**Comment by HenrikBengtsson** [comment]
Sorry, false alarm.  It install fine now.  (There was certainly an error
during build/install, but I just assumed there was a broken commit on top
and didn't investigate further. Could be that BBmisc was locked by another
session or something. yada yada yada)

**Comment by berndbischl** [comment]
@HenrikBengtsson 

Are we done here? Close?

**Comment by HenrikBengtsson** [comment]
I'm not sure/cannot remember and I won't have time to check back on this one until late next week or so.

**Comment by HenrikBengtsson** [comment]
Expired / Closing ... last task was on me and I don't recall what I should check.
