### ISSUE TITLE
SUGGESTION: Git Workflow

### ISSUE THREAD

**Issue by HenrikBengtsson** [tudo-r/BatchJobs#69]
I've noticed that you do all your commits to the 'master' branch and that you don't use/push any other branches.  May I suggest to use the following git workflow proposed in:

  [A successful Git branching model](http://nvie.com/posts/a-successful-git-branching-model/), Vincent Driessen, 2010

There is even a [git-flow](http://danielkummer.github.io/git-flow-cheatsheet/) add-on to Git that makes it even easier to adapt the workflow.  That tool is not needed, but I find it neat.

The main ideas for branches are:
* `master`: is identical to the official release version, i.e. what's on CRAN. Rule: never commit do this branch; only merge from release branches (**this** rule I found very useful).
* `develop`: is for everyday commits and general development.  This is pretty much how you use the master branch today.
* e.g. `release/1.6`: when you're about the release BatchJobs 1.6, you do `git flow release start 1.6` to create this branch. The you run all your tests. You probably find some minor issues that you fix and commit to this branch. Then you submit to CRAN and wait. When on CRAN, you do `git flow release finish 1.6` and the commits in this branch will be merged into the `master` and `develop` branches, and this branch will be automatically deleted.  This version/commit will also be git tagged as `1.6`, which can be installed as `install_github('tudo-r/BatchJobs@1.6')`.
* e.g. `feature/load-only`: when you want to try out a new feature that might side-track from the main development, use `git flow feature start load-only` to create a new feature branch.  Play around with it.  If it works, merge it back into `develop` and "finish" it.

**Comment by berndbischl** [comment]
I would like to do it like this:

Use the master for pushes which are "complete" and do not break stuff.
Everything unfinished must go into a devel branch. And will only be merged when done.
