### ISSUE TITLE
Is a shared file system essential for all types of cluster functions?

### ISSUE THREAD

**Issue by HenrikBengtsson** [tudo-r/BatchJobs#71]
Is BatchJobs and it's Registry mechanism written such that all "compute" nodes need to be on the same shared file system?  I've noticed this is an explicit requirement stated for "all machines" on an [SSH Cluster](https://github.com/tudo-r/BatchJobs/wiki/SSH-Cluster).  But this is true for all [cluster functions](https://github.com/tudo-r/BatchJobs/wiki/Cluster-Functions), correct?

**Comment by berndbischl** [comment]
> Is BatchJobs and it's Registry mechanism written such that all "compute" nodes need to be on the 
> same shared file system? I've noticed this is an explicit requirement stated for "all machines" on an 
> SSH Cluster. But this is true for all cluster functions, correct?

Yes. We dislike that fact and would like to extend it at some point. 

Also note, that I have worked on Azure, where this was not given. We then setup sshfs.....
I had a bad feeling about this beacause of delays and timeouts and so on.
But we never saw any problems in that project, luckily.

**Comment by HenrikBengtsson** [comment]
Ok, thanks for the confirmation.  Maybe this could be made a bit more explicit in the help/README.md.

**Comment by berndbischl** [comment]
added this to FAQ
