### ISSUE TITLE
Get error in RStudio GUI when the code works fine with R CLI

### ISSUE THREAD

**Issue by fengliteraproc** [tudo-r/BatchJobs#73]
HI Team,
I tried the example in BatchJobs package as below. R CLI works all right "R CMD BATCH ls11.R". But if I run this in RStudio GUI, I got below error:

Error in system2(command = command, args = args, stdout = stdout, stderr = stderr,  : 
  error in running command

Can any one shine some lights? thanks,

Details: 
###
File ls11.R
###
library(BatchJobs)
source("/home/openlava/r-openlava/BatchJobs-master/external_tests/helpers.R")

conf = BatchJobs:::getBatchJobsConf()
conf$mail.start = conf$mail.done = conf$mail.error = "none"

conf$cluster.functions = makeClusterFunctionsLSF("/home/openlava/r-openlava/BatchJobs-master/examples/cfLSF/ls11.tmpl")
doExternalTest(whitespace=FALSE, sleep.master=15, n=2)

###
File ls11.tmpl
###
#BSUB -J <%= job.name %>[1-<%= arrayjobs %>]   # name of the job / array jobs
#BSUB -o <%= log.file %>                       # output is sent to logfile, stdout + stderr by default

# very simple system, no resources....

# we merge R output with stdout from LSF, which gets then logged via -o option
R CMD BATCH  "<%= rscript %>" /dev/stdout

Thanks for your input.

Feng

**Comment by mllg** [comment]
What operating system are you running RStudio on?

**Comment by fengliteraproc** [comment]
thank you Michel. I've just fixed this. it's because of the ENV varialbes not set for bjobs command.
need to add below lines to /etc/R/Rprofile.site

.First <- function(){
 Sys.setenv(PATH="/opt/openlava/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/openlava-2.2/bin")
 Sys.setenv(LD_LIBRARY_PATH="/usr/local/openmpi/lib")
}

**Comment by berndbischl** [comment]
@fengliteraproc 

what is the status here? close?

**Comment by fengliteraproc** [comment]
close it please.
