### ISSUE TITLE
Shows Torque configuration but still getting errors

### ISSUE THREAD

**Issue by llucas1985** [tudo-r/BatchJobs#86]
I am following this blog (http://www.r-bloggers.com/configuring-the-r-batchjobs-package-for-torque-batch-queues/) to run a distributed job over a remote HPC cluster that uses TORQUE, and I have followed up to Step 3 and have successfully configured BatchJobs to Torque but I'm getting an error when I run Step 4 and I don't know what it means.  I am running "R version 3.1.2 (2014-10-31)".

Thanks, 
Lindsay

CODE:
> getConfig()
BatchJobs configuration:
  cluster functions: Torque
  mail.from: 
  mail.to: 
  mail.start: none
  mail.done: none
  mail.error: none
  default.resources: 
  debug: FALSE
  raise.warnings: FALSE
  staged.queries: TRUE
  max.concurrent.jobs: Inf
  fs.timeout: NA
> library(BatchJobs)
> loadConfig()
Sourcing configuration file: '.BatchJobs.R'
> starts <- replicate(10, rnorm(100), simplify = FALSE)
> myFun  <- function(start) { median(start) }
> reg <- makeRegistry(id = "batchtest5")
Creating dir: /home/llucas/jobs/batchtest5-files
Saving registry: /home/llucas/jobs/batchtest5-files/registry.RData
> ids  <- batchMap(reg, myFun, starts)
Adding 10 jobs to DB.
Warning in checkUserFunction(fun) :
  The environment of provided function exceeds 10Mb.
> done <- submitJobs(reg, resources = list(nodes = 1))
OS cmd: qselect -u $USER -s EHQRTW
Error in system2(command = command, args = args, stdout = stdout, stderr = stderr,  : 
  error in running command
OS result:
[1] "Error in system2(command = command, args = args, stdout = stdout, stderr = stderr,  : \n  error in running command\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError in system2(command = command, args = args, stdout = stdout, stderr = stderr,     wait = wait, ...): error in running command>
Error in runOSCommandLinux(list.jobs.cmd[1L], list.jobs.cmd[-1L]) : 
  Error in runLinuxOSCommand: Error in system2(command = command, args = args, stdout = stdout, stderr = stderr,  : 
  error in running command
 (cmd: qselect || args: -u $USER,-s EHQRTW)

**Comment by berndbischl** [comment]
Hi. 

BJ uses at some point shell commands to operate torque. This is what you see here. Now whether this works or not depends on your configured system so it is a bit hard for us to say / check. This is also why we in general allow the user to change the cluster.functions for their system.

Nevertheless if you have a somewhat standard torque system, this should run.
a) Set debug = TRUE for now so you can see better what happens
b) Create a very simple test case with just 1 job and submit it
c) watch the commands and where it breaks. Then try to run the command in a shell / bash on your own manually. You should now really see what is wrong I hope.

**Comment by berndbischl** [comment]
I mean we kinda already have a good guess that this

(cmd: qselect || args: -u $USER,-s EHQRTW)

does not work. Can you run this command? It displays all of your jobs on the system

**Comment by berndbischl** [comment]
Note that you need to put in 

qselect -u $USER -s EHQRTW

**Comment by berndbischl** [comment]
No answer, closing for now. Please reopen if you have new info.
