### ISSUE TITLE
Release updated version to CRAN

### ISSUE THREAD

**Issue by gmbecker** [tudo-r/BatchJobs#94]
Thanks for incorporating PR #88 . Is it possible to release a version of BatchJobs containing that change to CRAN? I'd like to make downstream changes to BiocParallel which makes use of this feature, but can't until the change propogates to CRAN.

Thanks!

**Comment by berndbischl** [comment]
Hi.

I am sorry, I am not putting enough work into BatchJobs at the moment, due to teaching and work on mlr. 
I will really try, but I need to check a few things before I release to CRAN. 

I really hope weekend is possible. OK?

**Comment by gmbecker** [comment]
The weekend is fine, I understand being busy. Let me know if there's anything I can do to facilitate the process.

**Comment by berndbischl** [comment]
Ok the last release was in march. So that means I dont need to check much.
I will try to pull 1-2 minor things more in and release then on sunday.

**Comment by gmbecker** [comment]
Bernd,

Just checking in again. I'd really like to work on getting what I've done
into Bioconductor, but it requires the change made by my pull request a
while ago.

Are you close to a state where you can release a version containing that
change to CRAN?

Thanks,
~G

On Wed, Jun 10, 2015 at 10:25 AM, Bernd Bischl <notifications@github.com>
wrote:

> Ok the last release was in march. So that means I dont need to check much.
> I will try to pull 1-2 minor things more in and release then on sunday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tudo-r/BatchJobs/issues/94#issuecomment-110843617>.
>



-- 
Gabriel Becker, PhD
Computational Biologist
Bioinformatics and Computational Biology
Genentech, Inc.

**Comment by gmbecker** [comment]
Bernd,

Is there an eta for getting a new version of BatchJobs on CRAN?

**Comment by HenrikBengtsson** [comment]
FYI, I think this issue can be closed.
